### ISSUE TITLE
search fields should be marked as such

### ISSUE THREAD

**Issue by fbstj** [17thshard/palanaeum#7]
the text search boxes should be marked as type 'search' to enable them to be cleared easily

**Comment by mhalverson** [comment]
Not sure I understand what you mean by 'enable them to be cleared easily'... can you try saying it in a different way?

**Comment by burnhamaj** [comment]
It looks to me like the search box in the header and on the search page both are type="search". A little x appears on the right to clear out what has been typed. I'm not sure when this change was made, but I think this can be closed.
