### ISSUE TITLE
Make adding tags Arcanist-only feature

### ISSUE THREAD

**Issue by jofwu** [17thshard/palanaeum#85]
An ongoing issue with tags is that people often create redundant tags or other new tags that we don't want. I think the plan was for Arcanists to simply check these when approving entries, but we've been very inconsistent about this. (in part because checking if the suggested tags already exist is a tedious process.)

We might need to have further discussion on exactly how this problem should be solved, but one simple change that would _help_ is to make it so that only Arcanists can create new tags. This way Arcanists can be certain that suggested tags already exist, and they only need to make sure proposed tags are applicable to the entry.

**Comment by LewsTherinTelescope** [comment]
Looks like this was resolved in 90924375e445dd58e7c51d7e6c27bfde6a910f57.
